name: Dockerize
on:
  push:
    branches: [ main ]
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push wordpress php 8.0
        uses: docker/build-push-action@v3
        with:
          context: ./php8.0
          push: true
          tags: yiiman/wordpress-ioncube:php8.0
          no-cache: true
          #test comment
      -
        name: Build and push wordpress php 8.1
        uses: docker/build-push-action@v3
        with:
          context: ./php8.1
          push: true
          tags: yiiman/wordpress-ioncube:php8.1
          no-cache: true
          #test comment
      -
        name: Build and push wordpress php 8.2
        uses: docker/build-push-action@v3
        with:
          context: ./php8.2
          push: true
          tags: yiiman/wordpress-ioncube:php8.2
          no-cache: true
          #test comment
